name: Mirror main to gh-pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Mirror changes to gh-pages
        run: |
          git checkout gh-pages
          git merge --no-edit main
          git push origin gh-pages
