name: Update gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages:gh-pages

      - name: Merge changes from main to gh-pages
        run: |
          git checkout gh-pages
          git merge main --no-commit --no-ff

          # Resolve conflicts if any
          git commit -m "Update from main branch"

      - name: Push changes to gh-pages
        run: |
          git push origin gh-pages
