name: Sync gh-pages with main

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Sync changes
        run: |
          cp -r ./main/* ./gh-pages/
          cd gh-pages
          git add .
          git commit -m "Sync changes from main"
          git push origin gh-pages
