name: Update gh-pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to gh-pages
        run: |
          git checkout -b gh-pages
          git merge main --no-edit
          git push origin gh-pages
