name: Update gh-pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Merge changes
        run: |
          cd gh-pages
          git fetch origin gh-pages
          git merge origin/gh-pages --no-edit

      - name: Push changes
        run: |
          cd gh-pages
          git push origin gh-pages
